In [1]:
import numpy as np
import cv2

In [3]:
img = cv2.imread('./data/friends.jpg')
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
haar = cv2.CascadeClassifier('./data/haarcascade_frontalface_default.xml')

In [8]:
image = img.copy()

# 1 - convert to gray
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# 2 - apply grayscale image to cascade classifier
face_rect = haar.detectMultiScale(gray, 1.3, 5)

# 3 - draw bounding box
for x, y, w, h in face_rect:
    cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)

cv2.imshow('detected', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
print(face_rect)

[[149 259  30  30]
 [126   4  68  68]
 [128 107  96  96]
 [255  90  95  95]
 [407  92  95  95]]


In [13]:
# Real time face detection

cap = cv2.VideoCapture('./data/video.mp4')

while True:
    ret, frame = cap.read()
    if ret == False:
        break

    movie = frame.copy()

    # 1 - convert to gray
    gray = cv2.cvtColor(movie, cv2.COLOR_BGR2GRAY)

    # 2 - apply grayscale image to cascade classifier
    face_rect = haar.detectMultiScale(gray, 1.3, 5)

    # 3 - draw bounding box
    for x, y, w, h in face_rect:
        cv2.rectangle(movie, (x, y), (x+w, y+h), (0, 255, 0), 2)
    
    cv2.imshow('face detection', movie)

    if cv2.waitKey(10) == 27:
        break

cap.release()
cv2.destroyAllWindows()