In [14]:
# Importando a biblioteca NumPy para manipulação de arrays e a biblioteca OpenCV para processamento de imagens e vídeo.
import numpy as np
import cv2

In [15]:
# Carrega a imagem 'friends.jpg' do diretório './data' usando a função imread() do OpenCV.
img = cv2.imread('./data/friends.jpg')

# Exibe a imagem carregada em uma janela com o título 'image'.
cv2.imshow('image', img)

# Espera indefinidamente até que uma tecla seja pressionada, para permitir visualização da imagem.
cv2.waitKey(0)

# Fecha todas as janelas de exibição de imagens abertas pelo OpenCV.
cv2.destroyAllWindows()

In [16]:
# Carrega o classificador Haar Cascade para detecção de faces, utilizando o arquivo XML correspondente.
haar = cv2.CascadeClassifier('./data/haarcascade_frontalface_default.xml')

In [17]:
# Faz uma cópia da imagem original para não modificar a imagem original.
image = img.copy()

# 1 - Converte a imagem copiada para escala de cinza, o que é necessário para o classificador Haar.
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# 2 - Aplica a imagem em escala de cinza ao classificador Haar, detectando possíveis regiões de rosto.
# O método detectMultiScale retorna as coordenadas dos retângulos que delimitam os rostos.
face_rect = haar.detectMultiScale(gray, 1.3, 5)

# 3 - Desenha um retângulo verde ao redor de cada rosto detectado.
# O laço for percorre as coordenadas de cada rosto detectado e desenha o retângulo.
for x, y, w, h in face_rect:
    cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)  # (x, y) é o ponto superior esquerdo, (x+w, y+h) é o ponto inferior direito

# Exibe a imagem com os rostos detectados e delimitados em uma nova janela chamada 'detected'.
cv2.imshow('detected', image)

# Espera indefinidamente até que uma tecla seja pressionada.
cv2.waitKey(0)

# Fecha todas as janelas abertas pelo OpenCV.
cv2.destroyAllWindows()

In [6]:
print(face_rect)

[[149 259  30  30]
 [126   4  68  68]
 [128 107  96  96]
 [255  90  95  95]
 [407  92  95  95]]


In [18]:
# Inicia a captura de um vídeo do arquivo 'video.mp4' no diretório './data'.
cap = cv2.VideoCapture('./data/video.mp4')

# Laço while para processar frame a frame do vídeo até que ele termine.
while True:
    # Lê um frame do vídeo.
    ret, frame = cap.read()

    # Se não houver mais frames, ret será False e o laço será encerrado.
    if ret == False:
        break

    # Faz uma cópia do frame atual para preservá-lo.
    movie = frame.copy()

    # 1 - Converte o frame copiado para escala de cinza para detecção de rosto.
    gray = cv2.cvtColor(movie, cv2.COLOR_BGR2GRAY)

    # 2 - Aplica a imagem em escala de cinza ao classificador Haar para detectar rostos no frame atual.
    face_rect = haar.detectMultiScale(gray, 1.3, 5)

    # 3 - Desenha um retângulo verde ao redor de cada rosto detectado no frame atual.
    for x, y, w, h in face_rect:
        cv2.rectangle(movie, (x, y), (x+w, y+h), (0, 255, 0), 2)  # (x, y) é o ponto superior esquerdo, (x+w, y+h) é o ponto inferior direito

    # Exibe o frame processado com a detecção de rostos na janela 'face detection'.
    cv2.imshow('face detection', movie)

    # Se a tecla 'Esc' (código 27) for pressionada, o laço é encerrado.
    if cv2.waitKey(10) == 27:
        break

# Libera o objeto de captura de vídeo e fecha todas as janelas abertas.
cap.release()
cv2.destroyAllWindows()